version: "3.5"

services:
  web:
    image: webdevops/php-apache:7.4
    working_dir: /app
    ports:
      - 8000:80
    volumes:
      - .:/app
    environment:
      WEB_DOCUMENT_ROOT: /app
      WEB_DOCUMENT_INDEX: index.php