<?php


namespace Test;


use App\User;
use PHPUnit\Framework\TestCase;

class UserTest extends TestCase
{

    private $user1;
    private $user2;

    public function setUp(): void
    {
        $this->user1 = new User('Popo', 'Johnny', 'jojo@adventure.jp', 15);
        $this->user2 = new User('Popo', 'Johnny', 'jojo', 22);
    }

    public function testIsValid()
    {
        $this->assertTrue($this->user1->isValid());
    }

    public function testIsNotValid()
    {
        $this->expectException(\Exception::class);
        $this->user2->isValid();
    }

    public function tearDown(): void
    {
        unset($this->user1);
        unset($this->user2);
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}